### ISSUE TITLE
Лучше это всё писать после координат и версии

### ISSUE THREAD

**Issue by coursar** [ElenaVeselovskaya/kfc-food#3]
https://github.com/ElenaVeselovskaya/kfc-food/blob/5a20443709171fa0b815a51f4a270e3274d77f3a/pom.xml#L6-L9

**Comment by ElenaVeselovskaya** [comment]
@coursar, забыла добавить 'fixes' при пуше
#2 и #3 исправлены

**Comment by coursar** [comment]
Так всё равно закрывайте, зачем оставлять открытым и назначать на меня?
